{
 "title": "Envoy global",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "envoy_namespace",
    "query": {
     "query": "label_values(envoy_server_version, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total{namespace=\"$envoy_namespace\"}[1m]))",
     "legendFormat": "Globlal RPS"
    },
    {
     "expr": "sum(rate(envoy_cluster_health_check_attempt{namespace=\"$envoy_namespace\"}[1m]))",
     "legendFormat": "Global HC RPS"
    },
    {
     "expr": "sum(rate(envoy_http_rq_total{namespace=\"$envoy_namespace\"}[1m]))",
     "legendFormat": "Global Routed RPS"
    }
   ]
  },
  {
   "title": "Global CPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_cx_total{namespace=\"$envoy_namespace\"}[1m]))",
     "legendFormat": "Global CPS"
    }
   ]
  },
  {
   "title": "Success Rate (non-5xx responses)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - (sum(rate(envoy_http_downstream_rq_xx{response_code_class=\"5\",namespace=\"$envoy_namespace\"}[1m])) / sum(rate(envoy_http_downstream_rq_xx{namespace=\"$envoy_namespace\"}[1m]))))",
     "legendFormat": "SR"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active{namespace=\"$envoy_namespace\"})",
     "legendFormat": "Global Connections"
    },
    {
     "expr": "sum(envoy_server_parent_connections{namespace=\"$envoy_namespace\"})",
     "legendFormat": "Global Parent Connections"
    }
   ]
  },
  {
   "title": "Upstream failures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_failure_eject{namespace=\"$envoy_namespace\"}[1m]))",
     "legendFormat": "Pending failure ejection"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_overflow{namespace=\"$envoy_namespace\"}[1m]))",
     "legendFormat": "Pending Overflow"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_connect_timeout{namespace=\"$envoy_namespace\"}[1m]))",
     "legendFormat": "Connect Timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_timeout{namespace=\"$envoy_namespace\"}[1m]))",
     "legendFormat": "Request Timeout"
    }
   ]
  },
  {
   "title": "Upstream Retries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry{namespace=\"$envoy_namespace\"}[1m]))",
     "legendFormat": "Retry"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_success{namespace=\"$envoy_namespace\"}[1m]))",
     "legendFormat": "Retry Success"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_overflow{namespace=\"$envoy_namespace\"}[1m]))",
     "legendFormat": "Retry Overflow"
    }
   ]
  },
  {
   "title": "Outlier Detection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_outlier_detection_ejections_enforced_total{namespace=\"$envoy_namespace\"}[1m]))",
     "legendFormat": "Total Ejections"
    },
    {
     "expr": "sum(rate(envoy_cluster_outlier_detection_ejections_overflow{namespace=\"$envoy_namespace\"}[1m]))",
     "legendFormat": "Total Ejection Overflows"
    }
   ]
  },
  {
   "title": "Health Checks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((sum(rate(envoy_cluster_health_check_success{namespace=\"$envoy_namespace\"}[1m])) / sum(rate(envoy_cluster_health_check_attempt{namespace=\"$envoy_namespace\"}[1m]))))",
     "legendFormat": "Success Rate"
    }
   ]
  }
 ]
}